# autogenerated by txs
#include:iftex
#include:kvoptions
#include:pdfescape
\AccSuppSetup#S
\ActualTextDriverDefault#S
\BeginAccSupp{arg1}#S
\EndAccSupp{arg1}#S
\csname#S
\x#S
\__hook pdfescape#S
\unprocessedoptions-pdfescape.sty#S
accsupp-pdftex.def#S
accsupp.cfg#S
csnameendcsname#S
pdfescape.sty#S
