# autogenerated by txs
\MakeRobust{arg1}#S
\TextOrMath#S
\TextOrMath{arg1}{arg2}#S
\addpenalty{arg1}#S
\csname#S
\em#S
\eminnershape#S
\firstmark#S
\noexpand#S
\setlength{arg1}{arg2}#S
\textsubscript{arg1}#S
\topmark#S
\\fixltxe+fixltx2e+IIR#S
