# autogenerated by txs
#include:textcomp
#include:xkeyval
\altzero#S
\filedate#S
\fileversion#S
\zifour#S
\__hook textcomp#S
\__hook xkeyval#S
\unprocessedoptions-textcomp.sty#S
\unprocessedoptions-xkeyval.sty#S
csnameendcsname#S
textcomp.sty#S
xkeyval.sty#S
