# autogenerated by txs
#include:graphics
\begin{importantnote}#S
\begin{informationnote}#S
\begin{warningnote}#S
\boxdbg{arg1}#S
\buildcontainer{arg1}{arg2}#S
\buildiconbox{arg1}#S
\buildiconframe{arg1}#S
\buildnotes{arg1}{arg2}#S
\buildtextframe{arg1}#S
\buildvcontainer{arg1}{arg2}#S
\calccontainerht{arg1}{arg2}#S
\end{importantnote}#S
\end{informationnote}#S
\end{warningnote}#S
\noteskip#S
\thenotecnt
\__hook graphics#S
\unprocessedoptions-graphics.sty#S
csnameendcsname#S
graphics.sty#S
