# autogenerated by txs
#include:kvoptions
\noclub#S
\noclub[opt]#S
\nowidow#S
\nowidow[opt]#S
\setnoclub#S
\setnoclub[opt]#S
\setnowidow#S
\setnowidow[opt]#S
\\noclub#S
\\nowidow#S
\\setnoclub#S
\\setnowidow#S
\x#S
