# autogenerated by txs
#include:calc
#include:ifthen
\pbox{arg1}#S
\settominwidth[opt]{arg1}{arg2}#S
\settominwidth{arg1}{arg2}#S
\widthofpbox{arg1}#S
\\pbox #S
\\settominwidth#S
\__hook calc#S
\__hook ifthen#S
\pbox #S
\unprocessedoptions-calc.sty#S
\unprocessedoptions-ifthen.sty#S
calc.sty#S
csnameendcsname#S
ifthen.sty#S
