# autogenerated by txs
#include:adjcalc
#include:collectbox
#include:graphicx
\clipbox#S
\expandafter#S
\marginbox#S
\trimbox#S
\__hook adjcalc#S
\__hook collectbox#S
\__hook graphicx#S
\clipbox*#S
\marginbox*#S
\trimbox*#S
\unprocessedoptions-adjcalc.sty#S
\unprocessedoptions-collectbox.sty#S
\unprocessedoptions-graphicx.sty#S
adjcalc.sty#S
collectbox.sty#S
csnameendcsname#S
graphicx.sty#S
tc-pdftex.def#S
