; TODO WLAN-Fläche soll Netzwerkmanager öffnen
; TODO Aktualisierungs-Fläche soll Aktualisierungsmanager öffnen
; TODO Was ist "tray"?




[colors]
bg = #16161e
bg-alt = #20212C
fg = #acb0d0
fg-alt = #5D5E72

red = #ff7a93

trans = #00000000
semi-trans-black = #cc000000

shade-1 = #32344a
shade-2 = #444b6a
shade-3 = #787c99
shade-4 = #CACACE
shade-5 = #acb0d0


[bar/main]
width = 100%
height = 40
offset-y = 0
top = true
fixed-center = true

locale = de_DE.utf-8

; wm-restack = bspwm

override-redirect = false

scroll-up = next
scroll-down = prev

enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

; font-0 = "JetBrainsMono Nerd Font:style=Regular:size=10;2"
font-0 = "FiraCode Nerd Font:style=Regular:size=15"
font-1 = "FiraCode Nerd Font:style=Regular:size=16"
; font-1 = "JetBrainsMono Nerd Font:style=Bold:size=10;2"
; font-2 = "JetBrainsMono Nerd Font:size=19;5"
; font-3 = "Material Icons Outlined:9;4"
; font-4 = "Material Icons Round:9;4"
; font-5 = "Source Han Sans CN:size=9;2"

modules-left = session info-hlwm-workspaces
modules-center = 
modules-right = updates wlan battery pulseaudio date
; filesystem

tray-position = right 

cursor-click = pointer


[bar/external]
monitor = HDMI1
modules-right = wlan pulseaudio margin session
inherit = bar/main


[settings]
screenchange-reload = true
format-padding = 1


[module/info-hlwm-workspaces]
; https://github.com/wlard/dotfiles/blob/master/polybar/config
type = custom/script
; https://github.com/wlard/dotfiles/blob/master/polybar/info-hlwm-workspaces/info-hlwm-workspaces.sh
exec = ~/.config/polybar/info-hlwm-workspaces.sh
; wenn "false" wird es nicht angezeigt
tail = true
scroll-up = herbstclient use_index -1 --skip-visible &
scroll-down = herbstclient use_index +1 --skip-visible &
label-active-font=1

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume> <bar-volume>
format-volume-prefix = " "
label-volume = %percentage:3%%
label-volume-foreground = ${root.foreground}

format-muted = <label-muted> <bar-volume>
format-muted-prefix = " "
format-muted-foreground = ${colors.fg-alt}
format-muted-background = ${colors.bg-alt}
label-muted-foreground = ${colors.fg-alt}
label-muted = %percentage:3%%

bar-volume-width = 10
; Es sind, glaube ich, nur 0-6 möglich
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #ff8888
bar-volume-foreground-6 = #ff0000
bar-volume-gradient = false
bar-volume-indicator = |
;bar-volume-indicator-font = 3
bar-volume-indicator-foreground = #ff
bar-volume-fill = -
;bar-volume-fill-font = 3
bar-volume-empty = -
;bar-volume-empty-font = 3
bar-volume-empty-foreground = ${colors.fg-alt}


[module/battery]
type = internal/battery
battery = BAT1
adapter = ADP1
full-at = 98
low-at = 30
format-full-prefix = 
; format-full = <label-charging>
format-full = %percentage:2%%
format-charging-prefix = 
format-charging = <label-charging>
label-charging = %percentage:2%%
label-charging-padding = 1
format-charging-foreground = ${colors.fg}
format-discharging = <ramp-capacity><label-discharging>
label-discharging = %percentage%%
label-discharging-padding = 1
format-discharging-foreground = ${colors.fg}
format-low = <ramp-capacity><label-discharging>
label-low-padding = 1
format-low-foreground = ${colors.red}
ramp-capacity-0 = ""
ramp-capacity-1 = "%{T2}%{T1}"
ramp-capacity-2 = "%{T2}%{T1}"
ramp-capacity-3 = "%{T2}%{T1}"
ramp-capacity-4 = "%{T2}%{T1}"
ramp-capacity-5 = ""
poll-interval = 5


[module/date]
type = internal/date
interval = 1
time = "%a, %b %d %H:%M"
format = <label>
format-foreground = ${colors.fg}
format-padding = 1
; format-prefix = %{T5}-%{T-}
format-prefix = " "
label = %{T1}%time%%{T-}
label-padding = 1


;[module/pulseaudio]
;; TODO Man kann auch eine Regleranzeige verwenden
;type = internal/pulseaudio
;interval = 5
;; Erlaube mehr als 100%
;use-ui-max = true
;
;format-volume = <label-volume>
;; TODO Es gibt bessere Lautsprecher-Embleme aber die funktionieren irgendwie nicht mit FiraCode. Deswegen evtl. per %{Tx} eine andere Schrift verwenden. Das Original nutzte %{T4}.
;; 	https://github.com/polybar/polybar/wiki/Formatting#font-t
;format-volume-prefix = 
;format-volume-prefix-foreground = ${colors.fg}
;label-volume = %{T1}%percentage%%%{T-}
;label-volume-foreground = ${colors.fg}
;label-volume-padding = 1
;
;format-muted = <label-muted>
;; analog
;format-muted-prefix = 
;format-muted-prefix-foreground = ${colors.fg-alt}
;label-muted = %{T1}%percentage%%%{T-}
;label-muted-foreground = ${colors.fg-alt}
;label-muted-padding = 1
;
;click-right = pavucontrol&

[module/session]
; type = custom/text
; 
; click-left = powermenu
; content = %{T4}%{T-}
; content-background = ${colors.shade-2}
; content-foreground = ${colors.shade-5}
; content-padding = 1

type = custom/menu
; Bestimmt Richtung, in der aufgezählt wird
expand-right = true
;format-spacing = 1
format-underline = #BF616A
label-open = "⏻"
label-open-foreground = #ECEFF4
label-close = "Abbrechen"
label-close-foreground = #EBCB8B
label-separator = "|"
label-separator-foreground = #A3BE8C
; Bereitschaft:  
menu-0-3 = "    "
menu-0-3-exec = #session.open.1
menu-0-1 = "  ⏻  "
menu-0-1-exec = #session.open.2
menu-0-2 = "    "
menu-0-2-exec = #session.open.3
menu-0-0 = "    "
menu-0-0-exec = #session.open.4
; #session.open.1
menu-1-0 = "Neustart"
menu-1-0-exec = reboot
; #session.open.2
menu-2-0 = "Herunterfahren"
menu-2-0-exec = poweroff
; #session.open.3
menu-3-0 = "Abmelden"
menu-3-0-exec = notify-send "Funktioniert noch nicht"
; #session.open.4
menu-4-0 = "Winterschlaf"
menu-4-0-exec = sudo systemctl hibernate

[module/wlan]
type = internal/network
interface = wlp0s20f3
interval = 1.0

format-connected-prefix = "󰖩"
format-connected = <label-connected>
; %essid% nur für Kabel-lose Verbindungen
label-connected = "%{A1:wifimenu:}%essid%%{A}"
label-connected-foreground = ${colors.fg}
label-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-padding = 1
label-disconnected = %{A1:wifimenu:}%{A}
label-disconnected-foreground = ${colors.shade-1}
label-disconnected-padding = 1
click-left = nm-connection-editor

[module/updates]
type = custom/script
exec = cat ~/.config/polybar/nmb_updates.txt
interval = 5.0

format = <label>
format-prefix = 
label = %output%
label-padding = 1

[module/filesystem]
type = internal/fs

mount-0 = /
interval = 30
warn-percentage = 90

format-mounted-prefix = 
label-mounted = %free%
label-mounted-padding = 1

format-warn-prefix = 
format-warn = <label-warn>
label-warn = %free%
label-warn-padding = 1
format-warn-foreground = ${colors.red}
